name: CI
on: push
jobs:
  test:
    name: Test on node ${{ matrix.perl_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl_version: ["5.28.2"]    
    steps:
    - uses: actions/checkout@v1
    - name: use Perl ${{ matrix.perl_version }}
      run: |
        mkdir plenv && \
        ls -a ~ && \
        pwd && \
        ls -a `pwd` && \
        wget -O plenv.tar.gz https://github.com/tokuhirom/plenv/archive/master.tar.gz && \
        tar --directory=./plenv --strip-components=1 -zxvf plenv.tar.gz && \
        wget -O perl-build.tar.gz https://github.com/tokuhirom/Perl-Build/archive/master.tar.gz && \
        mkdir -p ./plenv/plugins/perl-build && \
        tar --directory=./plenv/plugins/perl-build --strip-components=1 -zxvf perl-build.tar.gz && \
        export PLENV_ROOT=`pwd`/plenv
        env && \
        ./plenv/bin/plenv install ${{ matrix.perl_version }} && \
        ./plenv/bin/plenv local ${{ matrix.perl_version }} && \
        ./plenv/bin/plenv rehash && \
        perl -v
        
